# Generated by Django 2.2.4 on 2019-08-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=255, verbose_name='Responsavel')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=255, verbose_name='Telefone')),
                ('horario', models.CharField(max_length=255, verbose_name='Horario de Atendimento')),
                ('data', models.CharField(max_length=255, verbose_name='Data de Funcionamento')),
                ('motivo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
